### ISSUE TITLE
Loading a savegame locks Eidolon hand equipment slots

### ISSUE THREAD

**Issue by TheCowofEternalFlame** [Balkoth-dev/WOTR_MAKING_FRIENDS#4]
Loading a savegame with a Bipedal Eidolon with "Limbs, Arms" locks it's hand slots, preventing it from equipping weapons. On level up when it first gains the "Limbs, Arms" ability it can equip weapons like normal, it's only on loading a savegame that it breaks. Tested with no other mods enabled other than the mods this mod depends on and the issue still occurs.

Additionally the Debug option of "Reload" doesn't fix the issue either.

**Comment by TheCowofEternalFlame** [comment]
Additionally the Debug option of "Reload" doesn't fix the issue either.

**Comment by Xyrmes** [comment]
I'm also getting this issue, even buying the second Arms evolution didn't help.

**Comment by Balkoth-dev** [comment]
This has been fixed in 0.1.9. Please open a new ticket if you continue having issues.
