### ISSUE TITLE
First attack type bug

### ISSUE THREAD

**Issue by Seinra** [Balkoth-dev/WOTR_MAKING_FRIENDS#5]
Hello! I found a bug I didn't notice before. In my last run, I picked a Bulette (I think this is the name), which is a quadruped Eidolon that should start with a single "Bite" as its first and main attack, however, this is where I found the bug, its first main attack is an unarmed attack, and after this one it does a bite attack.

**Comment by Seinra** [comment]
Now I'm playing with a Bythos, a biped eidolon that replaces its main attack with Claws, but sometimes is still doing an Unarmed strike, this happens when it is not doing a full round attack.

**Comment by Balkoth-dev** [comment]
I have been unable to replicate this issue since it was reported. If you encounter this again please send more details. That said, I have added some extra functionality to bite attacks to make them able to be toggled as primary.
